
/*
 * TODO dokumentieren, wie man das hier einbindet wenn man es offsite haben will
 * (normalfall ist onsite, damit XC nicht loggen kann, wie viele Kaufconversions der Kunde hat)
 * 
 * TODO KOMPLETT UNGETESTET!  (EINFACH INS BLINDE GESCHRIEBEN)
 * 
 * */

var xcCT = [];
var _paq = _paq || [];
// localStorage is always in IE8, but JSON only in standards mode. So check for jQuery, too
var xcIsCompat = (typeof window.localStorage != 'undefined' && (window.JSON != 'undefined' || typeof $ == 'function'));
if(xcIsCompat){
	var xcJp = (typeof $ == 'function') ? $.parseJSON : window.JSON.parse;
	var xcData = xcJp(localStorage.getItem("excentos.analytics"))||{};
	xcData.pcount = 0;
	xcData.total = 0;
	_paq.push(["setDomains", "example.com"]);
	_paq.push(["setCookieNamePrefix", "_xcpk_"]);
	_paq.push(["setReferralCookieTimeout", xcData.metaData.referralAndLtcTimout]);
	_paq.push(["setSiteId", xcData.metaData.piwikSiteId]);
    _paq.push(["appendToTrackingUrl", "logTo="+xcData.metaData.projectId]);
    _paq.push(['trackGoal', 4]); // the "purchase" goal
}

function xcCheckProduct(orderid, product_uid, name, category, itemprice, quantity, product_vid){
	var findCookieProduct = function(pid){
        //returns ´false´ if the product id was not found, else the ´pid´ itself is being returned.
        return document.cookie.search("xcproducts_[^;]+?[=|&]"+pid+"(?:[|;&]|$)") == -1 ? false : pid;
    };
    var idU = findCookieProduct(product_vid) || findCookieProduct(product_uid);
    if(idU){
        xcCT.push([orderid, id, name, category, itemprice, quantity]);
    }

	var oldestAllowed = (new Date().getTime() / 1000) - (this.referralAndLtcTimout);
    var findStorageProduct = function(pid){
    	return (xcIsCompat 
    			&& xcData.productsWithInterest.hasOwnProperty(pid)
    			&& xcData.productsWithInterest[pid].lastInterestTime > oldestAllowed) ? false : pid;
    };
    var idP = findStorageProduct(product_vid) || findStorageProduct(product_uid);
    if(idP){
    	// addEcommerceItem(productSKU, productName, productCategory, price, quantity)
    	_paq.push(["addEcommerceItem", idP, name, category, itemprice, quantity]);
    	xcData.orderId = orderid;
    	xcData.total += itemprice;
    	xcData.pcount++;
    }
}
function xcTrackConversions(){
    if (typeof xcCT != "undefined" && xcCT.length > 0) {
        var script = document.createElement("script");
        script.src="https://analytics.excentos.de/log/trackingEngine.js";
        script.type="text/javascript";
        document.getElementsByTagName("head")[0].appendChild(script);
    }
    if (xcIsCompat && xcData.pcount > 0){
    	// TODO Total könnte auch im xcTracker Object gesetzt worden sein -> piwik-analogon rausfinden.
    	//  (interessant v.a. "total" weil da ein höherer Wert drinsteht potentiell)
    	/* xcTracker.utmtid; // transId
    		xcTracker.utmtto; // total
    		xcTracker.utmtst; // affiliation
    		xcTracker.utmttx; // tax
    		xcTracker.utmtsp; // shipping
    		xcTracker.utmtci; // city
    		xcTracker.utmtrg; // state
    		xcTracker.utmtco; // country
    	*/     	
    	// trackEcommerceOrder(orderId, grandTotal, subTotal, tax, shipping, discount)
    	_paq.push("trackEcommerceOrder", xcData.orderId, xcData.total, null, null, null, null);
    	// (code as generated by piwik):
	    var u="https://piwik.excentos.com/";
	    _paq.push(["setTrackerUrl", u+"piwik.php"]);
	    var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
	    g.defer=true; g.async=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
    }
}

// AB HIER KÖNNEN SIE DIE „xcCheckProduct()“ AUFRUFE ERZEUGEN
// ENDE STATISCHER BLOCK

// Beispiel dynamisch erzeugter Block:
// xcCheckProduct("ID-12345","TX801","Gefrierschrank TX 80l","Liebherr","153.99","2","TX801");
// xcCheckProduct("ID-4345","TX801-B","Zubehörteil TX 80l-B","Liebherr","15.90","1","TX801");
// xcTrackConversions();



